<?php
/**
 * This file was generated by the console.
 * No warranties are implied.
 */


namespace Sample;

class UserController
{

    public function createAction()
    {
        //create a record
    }

    public function retrieveAction()
    {
        //retrieve a record
    }

    public function updateAction()
    {
        //update a record
    }

    public function deleteAction()
    {
        //delete a record
    }


}

